[package]
name = "drpc-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.52"

[lib]
name = "drpc"
path = "src/lib.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"
