[package]
name = "drpc-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "drpc"
path = "src/lib.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"
